dist: trusty
sudo: required
addons:
  sonarqube:
    token:
      secure: "YHpi5ZtRDFlDtmLuJDO2tDli7lmL6erlg2EIjT1V/Hj5AFTXQ3VFgNnyqgvkbOQVzSshnWSSZLUfkUoWvCOMlReYg8mRB+tqgtTQROiCxL9r4Uxzpnkb4UWLJlbbRynMjgTbpAFWBYbfKMd7Z1qiPL74xXlXDkUbEYyxBCENKXY="
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
language: python
python:
  - "2.7"
#  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install scrutinizer-ocular"
# command to run tests
script:
  - coverage run --source=economicpy setup.py test

after_success:
  - coveralls
  - ocular