language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install scrutinizer-ocular"
# command to run tests
script:
  - coverage run --source=economicpy setup.py test

after_success:
  - coveralls
  - ocular